#-------------------------------
# Site Settings
title: emailht.ml
logo: "/images/logo_emailhtml_light.png" # You can add own logo. For example '/images/logo.png'.
logo_dark: "/images/logo_emailhtml_dark.png"
description: Hét adres voor up-to-date, robuuste, responsive en toegankelijke HTML en CSS voor e-mail
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.
language: nl

#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: "Over mij"
      url: "/over-mij/"
    - title: "Contact"
      url: "/contact/"
    - title: "Accessible Email Resources"
      url: "/accessible-email-resources/"


#-------------------------------
# Author Settings
author:
  author__name: Wilbert Heinen
  author__avatar: "/images/wilbert-heinen_headshot.jpeg"
  author__bio: Ik ben een email developer met een voorliefde voor lichtgewicht, responsive en toegankelijke HTML voor e-mail


#-------------------------------
# Links Section Settings
links:
  enable: true
  links__title: "Handige links"

links__item:
  - title: Email Geeks
    description: The Slack community where email marketers, designers, and developers meet to talk shop.
    image_url: "https://email.geeks.chat/img/open-graph.png"
    image_alt: Email Geeks
    link: "https://email.geeks.chat/"
  - title: Email Markup Consortium
    description: A community group working to improve the user experience, accessibility, performance, consistency, and reliability of email markup
    image_url: "https://emailmarkup.org/img/default-og-image.png"
    image_alt: Email Markup Consortium logo
    link: "https://emailmarkup.org/"
  - title: Parcel
    description: The Email Coding Platform
    image_url: "https://parcel.io/brand-guidelines-assets/parcel-logo.svg"
    image_alt: Parcel logo
    link: "https://parcel.io/"


#-------------------------------
# Hero Settings
hero:
  hero__title: Hoi, Ik ben <span>Wilbert Heinen</span> # Wrap text in a <span></span> tag to highlight and underline text.
  hero__job: Email Developer
  hero__description: Lichtgewicht, robuuste, responsive en toegankelijke HTML voor e-mail is helemaal mijn ding.
  hero__button__text: Meer over mij
  hero__button__link: "/over-mij/"
  hero__image: "/images/wilbert-heinen_headshot.jpeg"


#-------------------------------
# Gallery Footer Section
gallery:
  enable: true
  gallery__title: Ik werk graag met
  gallery__columns: "5" # You can change the number of gallery columns
  gallery__images:
    - alt: "deployteq"
      url: "/images/deployteq_logo_light.png"
      url__dark: "/images/deployteq_logo_dark.png"
      link: "https://www.deployteq.com"
    - alt: "Mark Kruisman Digital Business Solutions"
      url: "/images/logo_4_breed.png"
      url__dark: ""
      link: "https://www.markkruisman.nl"


#-------------------------------
# Newsletter
mailchimp:
  enable: false
  mailchimp__title: Subscribe to new posts # Add your Title
  mailchimp__text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
  mailchimp__identifier: "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__button__text: Subscribe


#-------------------------------
# Social Icons Settings
social:
#- {icon: "ion-logo-twitter", name: "Twitter", link: "https://twitter.com/wilbertheinen"}
- {icon: "ion-logo-github", name: "Github", link: "https://github.com/wilbertheinen"}
- {icon: "ion-logo-codepen", name: "Codepen", link: "https://codepen.io/wilbertheinen"}
- {icon: "ion-logo-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/in/wilbertheinen/"}

# Example of adding a new link to the author section and footer: - {icon: "ion-logo-dribbble", name: "Dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: hello@emailht.ml # Add your email for contant form
  description: Atega comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Atega theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id